#!/usr/bin/php
<?php
/**
 * UPLIFT
 *
 * Retire your FTP.
 *
 * @author Alexandre de Oliveira (chavedomundo@gmail.com)
 * @since 03/05/2010
 */

define('THIS_TO_BASE_DIR', '');
define('UPLIFT_CORE_DIR', THIS_TO_BASE_DIR.'upliftcore/');
define('DIRECTORIES_CONFIG_FILE', UPLIFT_CORE_DIR.'config/directories.php');
include_once(DIRECTORIES_CONFIG_FILE);

require_once(FUNCTIONS_DIR.'output.php');
require_once(FUNCTIONS_DIR.'shell_functions.php');
require_once(FUNCTIONS_DIR.'shell_inputs.php');
require_once(CLASS_DIR.'Shell.php');
require_once(CLASS_DIR.'Uplift.php');

$run = new Shell();
$command = $run->commands[0];
if( empty($command) )
    $command = "__empty";

if( is_file(COMMANDS_DIR.$command.'.php') )
{
    include(COMMANDS_DIR.$command.'.php');
    
    if( !class_exists($command) )
        exitOnUknownCommand($command);

    $uplift = new $command();
    
} else {
    exitOnUknownCommand($command);
}

echo "\n";
?>