#!/usr/bin/php
<?php
define('UPLIFT_CORE_DIR', 'upliftcore/');
    define('COMMANDS_DIR', UPLIFT_CORE_DIR.'commands/');
    define('LIB_DIR', UPLIFT_CORE_DIR.'lib/');
    define('CLASS_DIR', LIB_DIR.'class/');
    define('FUNCTIONS_DIR', LIB_DIR.'functions/');

define('CONFIG_FILE', '.uplift_config');
define('LIFTS_DIR', '.lifts/');

require_once(FUNCTIONS_DIR.'output.php');
require_once(FUNCTIONS_DIR.'shell_functions.php');
require_once(FUNCTIONS_DIR.'shell_inputs.php');
require_once(CLASS_DIR.'Shell.php');
require_once(CLASS_DIR.'Uplift.php');

$run = new Shell();
$command = $run->commands[0];
if( empty($command) )
    $command = "__empty";

if( is_file(COMMANDS_DIR.$command.'.php') )
{
    include(COMMANDS_DIR.$command.'.php');
    
    if( !class_exists($command) )
        exitOnUknownCommand($command);

    $uplift = new $command();
    
} else {
    exitOnUknownCommand($command);
}

echo "\n";
?>